# SPDX-License-Identifier: GPL-2.0-only
# platform driver
snd-soc-mt6572-afe-y := mt6572-afe-pcm.o
obj-$(CONFIG_SND_SOC_MT6572) += snd-soc-mt6572-afe.o

# machine driver
snd-soc-mt6572-machine-y := mt6572-machine.o
obj-$(CONFIG_SND_SOC_MT6572) += snd-soc-mt6572-machine.o
