# SPDX-License-Identifier: GPL-2.0
# Top-level connectivity Makefile; delegates to common/ and drv_wlan/
MTK_WLAN_SUPPORT := yes
MTK_WLAN_CHIP     := MT6620
export MTK_WLAN_SUPPORT MTK_WLAN_CHIP

obj-$(CONFIG_MTK_COMBO)       += common/
obj-$(CONFIG_MTK_COMBO_WIFI)  += drv_wlan/
